---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "sinple"
description: Performs variant calling to detect low-frequency variants using SiNPle, based on a Bayesian model.
keywords:
  - variant-calling
  - genomics
  - sequencing
tools:
  - "SiNPle":
      description: "SiNPle (Simplified Inference of Novel Polymorphisms from Large coveragE), a Bayesian-based tool for variant calling."
      homepage: "https://github.com/PaoloRibeca/SiNPle"
      doi: "10.3390/genes10080561"
      licence: ["GPL v3"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - pileup:
        type: file
        description: |
          Pileup file containing the reads and their quality scores.
          Example: `sample.pileup`
        pattern: "*.pileup"
        ontologies:
          - edam: "http://edamontology.org/format_3015"

output:
  - variants:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "variants.txt":
          type: file
          description: Text file containing detected variants.
          pattern: "variants.txt"
          ontologies:
            - edam: "http://edamontology.org/data_3498"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions.
          pattern: "versions.yml"

authors:
  - "@miqalvarez"
maintainers:
  - "@miqalvarez"
